### ISSUE TITLE
message text

### ISSUE THREAD

**Issue by deedos** [LUKKIEN/wagtailsocialfeed#13]
Hi.

I'm really new to wagtail and to this module. What happens is that in my views for facebook posts moderated (and for the  admin list as well) I only get the pictures and status text not the text from the body the posts themselves. How can I get the message body as in https://developers.facebook.com/docs/graph-api/reference/v2.9/user/feed (message) ?
thanks

**Comment by tleguijt** [comment]
Hi deedos,

I'm not sure actually which fields you are missing from the facebook stream, but you can tap into the `from_raw` method to see what data the module received from facebook and what data it selects from it.
https://github.com/LUKKIEN/wagtailsocialfeed/blob/master/wagtailsocialfeed/utils/feed/facebook.py#L76

If you're missing some essential fields we could add them to the FeedItem it returns.
For now, we've implemented the following post types:
```
    status
    photo
    link
    video
    offer
    event
```
from these post-types we retrieve the main-text. For example, in case of a 'photo' post type, it fetches the `description` field and uses it as text.

Since the FeedItems that are returned has to be very generic (since the source could be any platform - Twitter, Instagram, Facebook, you name it), the FeedItem itself doesn't contain too much detailed information.
However, it still provides a `original_data` field with, not surprisingly, provides the original data.
You could always use that field to fetch the info you need.

**Comment by deedos** [comment]
Hi. I think I located the matter:
There is no field "message" in the "raw data". For every post I fetch, i get the "story" as the "message", My original_data for a give post is as follow:
`{'FROM': {'ID': '195659600553965', 'NAME': 'SEM CENSURA'}, 'ICON': 'HTTPS://WWW.FACEBOOK.COM/IMAGES/ICONS/VIDEO.GIF', 'STORY': 'SEM CENSURA IS LIVE NOW.', 'UPDATED_TIME': '2017-05-12T21:03:10+0000', 'PICTURE': 'HTTPS://SCONTENT.XX.FBCDN.NET/V/T15.0-10/S130X130/18479120_1281396665313581_6947467981941112832_N.JPG?OH=38008681CF93F25EAB357553984781E7&OE=597F14B2', 'TYPE': 'VIDEO', 'IS_EXPIRED': FALSE, 'IS_HIDDEN': FALSE, 'STATUS_TYPE': 'ADDED_VIDEO', 'STORY_TAGS': [{'ID': '195659600553965', 'OFFSET': 0, 'TYPE': 'PAGE', 'NAME': 'SEM CENSURA', 'LENGTH': 11}], 'OBJECT_ID': '1281175958668985', 'PRIVACY': {'FRIENDS': '', 'DENY': '', 'DESCRIPTION': '', 'VALUE': '', 'ALLOW': ''}, 'ACTIONS': [{'LINK': 'HTTPS://WWW.FACEBOOK.COM/195659600553965/POSTS/1281175958668985', 'NAME': 'SHARE'}], 'CREATED_TIME': '2017-05-12T20:00:33+0000', 'LINK': 'HTTPS://WWW.FACEBOOK.COM/SEMCENSURATV/VIDEOS/1281175958668985/', 'ID': '195659600553965_1281175958668985'}`

How to overcome that ? thanks

**Comment by deedos** [comment]
It's missing "message" here https://github.com/LUKKIEN/wagtailsocialfeed/blob/master/wagtailsocialfeed/utils/conf.py
